/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:4dfd77bc-eec1-4874-b901-611e5a640cf8",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_hxUiWNvqo",
    "aws_user_pools_web_client_id": "6me59sienqvm30i9rsu5nrm0im",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mereketengue-images203608-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
