name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  release:
    name: Bump Version and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Pnpm
        run: corepack enable |
          corepack prepare pnpm@8.12.1 --activate

      # Pnpm dependencies cannot be cached until pnpm is installed
      # WORKAROUND: https://github.com/actions/setup-node/issues/531
      - name: Extract Cached Dependencies
        uses: actions/setup-node@v3
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Set Git user to Actions Bot
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel --yes --force --prod --token=${{ secrets.VERCEL_TOKEN }}
